name: dotnet-test-action
description: Test .NET solution or project
inputs:
  app_id:
    description: GitHub App ID to generate a token
    required: true
  app_private_key:
    description: Private key of the GitHub App to generate a token
    required: true
  github_token:
    description: GitHub token to access the repository
    required: true
  codecov-token:
    description: Token to upload code coverage to CodeCov
runs:
  using: "composite"
  steps:
    - name: Generate GitHub App Token
      uses: tibdex/github-app-token@v2
      id: generate-token
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.app_private_key }}
    - name: 📑 Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
        token: ${{ steps.generate-token.outputs.token }}
    - name: ⚙️ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - name: 🚚 Add GHCR as NuGet feed
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ inputs.github_token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
    - name: 🧪 Test
      run: dotnet test --collect:"XPlat Code Coverage" --logger "console;verbosity=detailed"
    - name: 📄 Get Coverage Files
      id: get_coverage_files
      if: matrix.os != 'windows-latest' && inputs.codecov-token != ''
      run: |
        coverage_files=$(find . -name 'coverage.cobertura.xml' -print0 | tr '\0' ',' | sed 's/,$//')
        echo "COVERAGE_FILES=$coverage_files" >> "$GITHUB_OUTPUT"
    - name: 📄 Get Coverage Files on Windows
      id: get_coverage_files_windows
      if: matrix.os == 'windows-latest' && inputs.codecov-token != ''
      run: |
        $coverage_files = Get-ChildItem -Path . -Recurse -Filter coverage.cobertura.xml -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName }
        $coverage_files = $coverage_files -join ','
        echo "COVERAGE_FILES=$coverage_files" >> "$GITHUB_OUTPUT"
    - name: 📄 Upload Code Coverage to CodeCov
      if: inputs.codecov-token != ''
      uses: codecov/codecov-action@v5
      with:
        files: ${{ steps.get_coverage_files.outputs.COVERAGE_FILES }}
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
